### ISSUE TITLE
Error `Cannot find module 'typescript'` after upgrade to 22.6.2

### ISSUE THREAD

**Issue by tmorehouse** [jest-community/eslint-plugin-jest#269]
```
#!/bin/bash -eo pipefail
yarn lint
yarn run v1.13.0
$ eslint --ext .js,.md,.vue ./
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/project/bootstrap-vue/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:17:25)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

Looks like `typescript` also needs to be moved to `dependencies`

**Comment by shazron** [comment]
I got the warning that I need `typescript` as a peer dep, so I installed it in my devDeps, but now I get this error: #268

**Comment by wmertens** [comment]
I guess it needs to be a peerDep because the version of typescript may differ per repo, but at least it should ignore missing typescript for repos that don't use typescript

**Comment by SimenB** [comment]
Should be a new release whenever https://www.githubstatus.com/incidents/nf4gcjtcsqdb is gone
