### ISSUE TITLE
[require-top-level-describe]: TypeError isDescribeEach is not a function

### ISSUE THREAD

**Issue by jdanil** [jest-community/eslint-plugin-jest#762]
eslint fails to run after upgrading to 24.1.4.

```
TypeError: (0 , _utils.isDescribeEach) is not a function
Occurred while linting [...]
    at CallExpression:exit ([...]/eslint-plugin-jest/lib/rules/require-top-level-describe.js:56:72)
```

Environment
- yarn 2.4.0
- node: 14.15.5
- eslint: 7.20.0
- eslint-plugin-jest: 24.1.4

I have public repo to reproduce it if its helpful.
https://github.com/jdanil/skunkworks

**Comment by G-Rath** [comment]
Ah I know what I'll have done - should have a fix out in 5

**Comment by jdanil** [comment]
Cheers @G-Rath!
